### ISSUE TITLE
[Feature request]: Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [LinwoodCloud/Flow#22]
### Is your feature request related to a problem? Please describe

Please support the Android 13 Themed App Icons feature.

### Describe your feature request!

![Screenshot_2023-08-03-11-19-36-680_de mm20 launcher2 release](https://github.com/LinwoodDev/Flow/assets/23485114/3c995c23-3cde-461f-813a-ad57e47ede1c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
you are the first issue creator :tada:
The icon is temporary, currently there are currently too many details.
I will put it on my todo list

**Comment by xmha97** [comment]
> you are the first issue creator 🎉 The icon is temporary, currently there are currently too many details. I will put it on my todo list

Thanks 🙏
I love your apps and use Butterfly and Flow.
Please do not give up on their development.

**Comment by CodeDoctorDE** [comment]
> > you are the first issue creator tada The icon is temporary, currently there are currently too many details. I will put it on my todo list
> 
> Thanks 🙏 I love your apps and use Butterfly and Flow. Please do not give up on their development.

<3
I will try to link both apps together in the future. Then you can link your notes to specific dates (for example a school calendar) and organize your notes there.
Feel free to join the linwood matrix/discord server.

**Comment by xmha97** [comment]
Wow, that's amazing.

**Comment by CodeDoctorDE** [comment]
Added in 0.3.1
