### ISSUE TITLE
[Bug]: Can't install on standard users

### ISSUE THREAD

**Issue by xmha97** [LinwoodCloud/Flow#23]
### What happened?

Hi please add a feature to the installer to install for current user.

### Version

0.2.0

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I copied the installer script from an older butterfly version.

For me: uncomment this line https://github.com/LinwoodDev/Flow/blob/develop/app/FlowSetup.iss#L31

**Comment by xmha97** [comment]
Ok, I hope fix this issue on next version. 🙏

**Comment by CodeDoctorDE** [comment]
I'm currently looking for a schedule when to release versions here.
This is currently in a preview state, and currently I don't have a real roadmap when to add things.
Feel free to create issues what you want to see here.

**Comment by CodeDoctorDE** [comment]
Fixed in the next version (maybe 0.2.1 or 0.3.0)

**Comment by xmha97** [comment]
Thanks 🙏
