### ISSUE TITLE
[Bug]: flow portable for linux - wrong shell script and wrong permissions

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [LinwoodCloud/Flow#24]
### What happened?

`flow` was not marked as executable in the tarball

the start script was not marked as executable and contained 
```
./butterfly.exe --path ./Data
```

which seems like the wrong script for the wrong operating system and misses the shebang selecting a shell

### Version

flow portable linux nightly 2023-08-04

### Platform

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Thanks for reporting.
I copied it from my other project and forgot to change the name.
I will add the shebang line to this file

**Comment by CodeDoctorDE** [comment]
Fixed in 0.2.1
