### ISSUE TITLE
[Documentation request]: license_ AGPL-3.0-only or GPL-3.0-only

### ISSUE THREAD

**Issue by ghost** [LinwoodCloud/Flow#27]
### To which page is your issue related?

https://gitlab.com/fdroid/fdroiddata/-/blame/master/metadata/dev.linwood.flow.nightly.yml#L3

### Describe your documentation request!

@CodeDoctorDE 
* **GPL-3.0-only** https://gitlab.com/fdroid/fdroiddata/-/blame/master/metadata/dev.linwood.flow.nightly.yml#L3
* **AGPL-3.0-only** https://github.com/LinwoodDev/Flow/blob/develop/LICENSE
* i need 100℅ clarity before changing it, please specify

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
It's Agpl 3.0 only, I will publish a merge request to the fdroid repo

**Comment by CodeDoctorDE** [comment]
Thanks for your note.
MR created: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13685

**Comment by CodeDoctorDE** [comment]
MR was merged. Thanks for this note
