### ISSUE TITLE
[Bug]: month view of the calendar shows previous month instead of the current month

### ISSUE THREAD

**Issue by justpeanuts** [LinwoodCloud/Flow#28]
### What happened?

There are also weird bugs in the whole month view - when you click a date it in a given month the selected date is that of the previous month - or something like that.

### Version

0.2.0

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hi,
Thanks for posting this bug. Can you look if this issue is also present in the newest web build? https://preview.flow.linwood.dev

**Comment by CodeDoctorDE** [comment]
Sorry for the long delay, fixed in 0.2.1
