### ISSUE TITLE
Amoled theme

### ISSUE THREAD

**Issue by Zaxx69** [LinwoodCloud/Flow#41]
### Describe your feature request!

Pure black theme 

### Additional context

![Screenshot_2023-12-28-17-55-51-93_2b0c70832456616f1f794bb05bb8d2fa](https://github.com/LinwoodDev/Flow/assets/138523882/68fed30d-69c3-4f1e-9151-18355a91f50a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Implemented in 0.2.2

**Comment by Zaxx69** [comment]
Thanks
