### ISSUE TITLE
The dashboard as back page 

### ISSUE THREAD

**Issue by Zaxx69** [LinwoodCloud/Flow#42]
### Is your feature request related to a problem? Please describe

Let's say l went from dashboard to places
Then i would press back
It should return to database
But currently it just closes the app

### Describe your feature request!

The database should be treated as a main page to return before closing the app

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Fixed in 0.3.0
